version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: hub-postgres
    restart: always
    environment:
      POSTGRES_DB: hub_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      - hub_postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    container_name: hub-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  hub_postgres_data: