spring:
  application:
    name: hub-server
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
    openfeign:
      circuitbreaker:
        enabled: true

    kafka1:
      bootstrap-servers: localhost:9092,localhost:9094,localhost:9096
      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        properties:
          spring.json.add.type.headers: true
      consumer:
        group-id: hub-stock-group
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  datasource:
    url: jdbc:postgresql://localhost:5433/hub_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 3s

eureka:
  instance:
    prefer-ip-address: false
    hostname: ${HOSTNAME:localhost}

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

resilience4j:
  retry:
    retry-aspect-order: 1
    configs:
      default:
        maxAttempts: 3
        waitDuration: 1s
        retryExceptions:
          - followMe.hub_server.stock.domain.exception.detail.VendorClientUnavailableException
          - followMe.hub_server.stock.domain.exception.detail.UserClientUnavailableException

    instances:
      vendor-server:
        baseConfig: default
      user-server:
        baseConfig: default


  circuitbreaker:
    circuit-breaker-aspect-order: 2
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5 # 5개 요청 기반
        minimumNumberOfCalls: 3 #3개 임시
        failureRateThreshold: 50 # 50% 실패 시 Open
        waitDurationInOpenState: 10s # Open 후 Half-Open까지 대기 시간
        ignore-exceptions:
          - feign.FeignException.NotFound
          - feign.FeignException.BadRequest

    instances:
      vendor-server:
        baseConfig: default
      user-server:
        baseConfig: default


logging:
  level:
    followMe.hub_server.stock: DEBUG

